export const SET_FOO = 'SET_FOO'

export const FETCH_STUDENTS_REQUESTED = 'FETCH_STUDENTS_REQUESTED';
export const FETCH_STUDENTS_SUCCEEDED = 'FETCH_STUDENTS_SUCCEEDED';

export const SET_STUDENT_FORM = 'SET_STUDENT_FORM';

export const CLEAR_STUDENT_FORM = 'CLEAR_STUDENT_FORM';

